server:
  port: 8090
  servlet:
    contextPath: /kpc

spring:
  cloud:
    stream:
      bindings:
        out-1:
          producer:
            partitionSelectorName: CustomPartitioner1
            partitionKeyExtractorName: CustomPartitionKeyExtractorClass1
            partitionCount: 3
          destination: producer-consumer-topic
          binder: kafka1
        dlq-out-1:
          producer:
            partitionSelectorName: CustomPartitioner2
            partitionKeyExtractorName: CustomPartitionKeyExtractorClass2
            partitionCount: 3
          destination: producer-consumer-topic-dlq-1
          binder: kafka2
        dlq-out-2:
          producer:
            partitionSelectorName: CustomPartitioner3
            partitionKeyExtractorName: CustomPartitionKeyExtractorClass2
            partitionCount: 3
          destination: producer-consumer-topic-dlq-2
          binder: kafka2
        in-1:
          consumer:
            partitioned: true
          destination: producer-consumer-topic
          group: producer-consumer-group-1
          binder: kafka1
        in-2:
          consumer:
            partitioned: true
          destination: producer-consumer-topic
          group: producer-consumer-group-2
          binder: kafka1
        dlq-in-1:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
          binder: kafka2
        dlq-in-2:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
          binder: kafka2
        dlq-in-3:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq-ex
          binder: kafka2
        dlq-in-4:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq-ex
          binder: kafka2
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
            spring.main.sources: com.sathish.KPC.messaging.consumer.DLQConsumer
        kafka2:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
            spring.main.sources: com.sathish.KPC.messaging.consumer.DLQConsumer
      kafka:
        binder:
          health-timeout: 60
        bindings:
          in-1:
            consumer:
              autoCommitOffset: false
          in-2:
            consumer:
              autoCommitOffset: false
          dlq-in-1:
            consumer:
              idleEventInterval: 1800000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-2:
            consumer:
              idleEventInterval: 3600000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-3:
            consumer:
              autoCommitOffset: false
          dlq-in-4:
            consumer:
              autoCommitOffset: false
      instance-count: 1
      instance-index: 0

logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.kafka: INFO
    org.springframework.integration: INFO
    org.springframework.spring-messaging: INFO
    org.springframework.retry: INFO